import { Classroom } from '../interfaces/classRoom';

export const dummyClassrooms: Classroom[] = [
  {
    classRoomId: 1,
    classRoomName: 'Sunshine Room',
    courseName: 'Droolers',
    childCareWorker: 'Maria Elena',
    childrenLimit: 10,
    startAge: 0,
    endAge: 1,
    children: [],
  },
  {
    classRoomId: 2,
    classRoomName: 'Rainbow Room',
    courseName: 'Walkers',
    childCareWorker: 'Francisca',
    childrenLimit: 12,
    startAge: 1,
    endAge: 2,
    children: [],
  },
  {
    classRoomId: 3,
    classRoomName: 'Adventure Zone',
    courseName: 'Wabblers',
    childCareWorker: 'Claudia',
    childrenLimit: 15,
    startAge: 2,
    endAge: 3,
    children: [],
  },
  {
    classRoomId: 4,
    classRoomName: 'Little Explorers',
    courseName: 'Go Wild',
    childCareWorker: 'Irene',
    childrenLimit: 12,
    startAge: 3,
    endAge: 4,
    children: [],
  },
  {
    classRoomId: 5,
    classRoomName: 'Cozy Corner',
    courseName: 'Hikers',
    childCareWorker: 'Natalia',
    childrenLimit: 10,
    startAge: 4,
    endAge: 5,
    children: [],
  },
  {
    classRoomId: 6,
    classRoomName: 'Tiny Tots Haven',
    courseName: 'Dancers',
    childCareWorker: 'Catalina',
    childrenLimit: 10,
    startAge: 5,
    endAge: 6,
    children: [],
  },
];
